export const DeptType = {
    Administration: "ADMINISTRATION",
    AnatomyCellBiology: "ANATOMY/CELL BIOLOGY",
    Anesthesiology: "ANESTHESIOLOGY",
    Biochemistry: "BIOCHEMISTRY",
    Biology: "BIOLOGY",
    BiomedicalEngineering: "BIOMEDICAL ENGINEERING",
    Biophysics: "BIOPHYSICS",
    BiostatisticsOtherMathSci: "BIOSTATISTICS & OTHER MATH SCI",
    Chemistry: "CHEMISTRY",
    Dentistry: "DENTISTRY",
    Dermatology: "DERMATOLOGY",
    EmergencyMedicine: "EMERGENCY MEDICINE",
    EngineeringAllTypes: "ENGINEERING (ALL TYPES)",
    FamilyMedicine: "FAMILY MEDICINE",
    Genetics: "GENETICS",
    InternalMedicineMedicine: "INTERNAL MEDICINE/MEDICINE",
    MicrobiologyImmunVirology: "MICROBIOLOGY/IMMUN/VIROLOGY",
    Miscellaneous: "MISCELLANEOUS",
    Neurology: "NEUROLOGY",
    Neurosciences: "NEUROSCIENCES",
    Neurosurgery: "NEUROSURGERY",
    NoCodeAssigned: "NO CODE ASSIGNED",
    None: "NONE",
    Nutrition: "NUTRITION",
    ObstetricsGynecology: "OBSTETRICS & GYNECOLOGY",
    Ophthalmology: "OPHTHALMOLOGY",
    Orthopedics: "ORTHOPEDICS",
    OtherBasicSciences: "OTHER BASIC SCIENCES",
    OtherClinicalSciences: "OTHER CLINICAL SCIENCES",
    OtherHealthProfessions: "OTHER HEALTH PROFESSIONS",
    Otolaryngology: "OTOLARYNGOLOGY",
    Pathology: "PATHOLOGY",
    Pediatrics: "PEDIATRICS",
    Pharmacology: "PHARMACOLOGY",
    PhysicalMedicineRehab: "PHYSICAL MEDICINE & REHAB",
    Physics: "PHYSICS",
    Physiology: "PHYSIOLOGY",
    PlasticSurgery: "PLASTIC SURGERY",
    Psychiatry: "PSYCHIATRY",
    Psychology: "PSYCHOLOGY",
    PublicHealthPrevMedicine: "PUBLIC HEALTH & PREV MEDICINE",
    RadiationDiagnosticOncology: "RADIATION-DIAGNOSTIC/ONCOLOGY",
    SocialSciences: "SOCIAL SCIENCES",
    Surgery: "SURGERY",
    Urology: "UROLOGY",
    VeterinarySciences: "VETERINARY SCIENCES",
    Zoology: "ZOOLOGY",
} as const;

export type DeptType = typeof DeptType[keyof typeof DeptType];
