export const OrgCountry = {
  Afghanistan: "AFGHANISTAN",
  Akrotiri: "AKROTIRI",
  Albania: "ALBANIA",
  Algeria: "ALGERIA",
  Andorra: "ANDORRA",
  Angola: "ANGOLA",
  Anguilla: "ANGUILLA",
  Antarctica: "ANTARCTICA",
  AntiguaBarbud: "ANTIGUA/BARBUD",
  Argentina: "ARGENTINA",
  Armenia: "ARMENIA",
  Aruba: "ARUBA",
  AshmorCartier: "ASHMOR/CARTIER",
  Australia: "AUSTRALIA",
  Austria: "AUSTRIA",
  Azerbaijan: "AZERBAIJAN",
  Bahamas: "BAHAMAS",
  Bahrain: "BAHRAIN",
  Bangladesh: "BANGLADESH",
  Barbados: "BARBADOS",
  BassasDIndia: "BASSAS D INDIA",
  Belarus: "BELARUS",
  Belgium: "BELGIUM",
  Belize: "BELIZE",
  Benin: "BENIN",
  Bermuda: "BERMUDA",
  Bhutan: "BHUTAN",
  Bolivia: "BOLIVIA",
  BonaireStEus: "BONAIRE/ST EUS",
  BosniaHerzeg: "BOSNIA/HERZEG",
  Botswana: "BOTSWANA",
  BouvetIsland: "BOUVET ISLAND",
  Brazil: "BRAZIL",
  BritishIot: "BRITISH IOT",
  BritishViIss: "BRITISH VI ISS",
  Brunei: "BRUNEI",
  Bulgaria: "BULGARIA",
  Burkina: "BURKINA",
  Burma: "BURMA",
  Burundi: "BURUNDI",
  CaboVerde: "CABO VERDE",
  Cambodia: "CAMBODIA",
  Cameroon: "CAMEROON",
  Canada: "CANADA",
  CaymanIslands: "CAYMAN ISLANDS",
  CentralAfrR: "CENTRAL AFR R",
  Chad: "CHAD",
  Chile: "CHILE",
  China: "CHINA",
  ChristmasIs: "CHRISTMAS IS",
  ClippertonIs: "CLIPPERTON IS",
  CocosKeelng: "COCOS (KEELNG)",
  Colombia: "COLOMBIA",
  Comoros: "COMOROS",
  Congo: "CONGO",
  CongoDemRep: "CONGO DEM REP",
  CookIslands: "COOK ISLANDS",
  CoralSeaIss: "CORAL SEA ISS",
  CostaRica: "COSTA RICA",
  CoteDIvoire: "COTE D'IVOIRE",
  Croatia: "CROATIA",
  Cuba: "CUBA",
  CuraAo: "CURAÇAO",
  Cyprus: "CYPRUS",
  CzechRepublic: "CZECH REPUBLIC",
  Denmark: "DENMARK",
  Dhekelia: "DHEKELIA",
  DiegoGarcia: "DIEGO GARCIA",
  Djibouti: "DJIBOUTI",
  Dominica: "DOMINICA",
  DominicanRep: "DOMINICAN REP",
  Ecuador: "ECUADOR",
  Egypt: "EGYPT",
  ElSalvador: "EL SALVADOR",
  Entity1: "ENTITY 1",
  Entity2: "ENTITY 2",
  Entity3: "ENTITY 3",
  Entity4: "ENTITY 4",
  Entity5: "ENTITY 5",
  Entity6: "ENTITY 6",
  EquatorGuinea: "EQUATOR GUINEA",
  Eritrea: "ERITREA",
  Estonia: "ESTONIA",
  Eswatini: "ESWATINI",
  Ethiopia: "ETHIOPIA",
  EurPatentOfc: "EUR PATENT OFC",
  EuropaIsland: "EUROPA ISLAND",
  FalklandIss: "FALKLAND ISS",
  FaroeIslands: "FAROE ISLANDS",
  FedMicronesia: "FED MICRONESIA",
  Fiji: "FIJI",
  Finland: "FINLAND",
  France: "FRANCE",
  FranceMetro: "FRANCE, METRO",
  FrenchGuiana: "FRENCH GUIANA",
  FrenchPolynes: "FRENCH POLYNES",
  FrenchSoAnt: "FRENCH SO/ANT",
  Gabon: "GABON",
  Gambia: "GAMBIA",
  GazaStrip: "GAZA STRIP",
  Georgia: "GEORGIA",
  Germany: "GERMANY",
  Ghana: "GHANA",
  Gibraltar: "GIBRALTAR",
  GloriosoIss: "GLORIOSO ISS",
  Greece: "GREECE",
  Greenland: "GREENLAND",
  Grenada: "GRENADA",
  Guadeloupe: "GUADELOUPE",
  Guatemala: "GUATEMALA",
  Guernsey: "GUERNSEY",
  Guinea: "GUINEA",
  GuineaBissau: "GUINEA-BISSAU",
  Guyana: "GUYANA",
  Haiti: "HAITI",
  HeardMcdonIs: "HEARD/MCDON IS",
  Honduras: "HONDURAS",
  HongKong: "HONG KONG",
  Hungary: "HUNGARY",
  Iceland: "ICELAND",
  India: "INDIA",
  Indonesia: "INDONESIA",
  Iran: "IRAN",
  Iraq: "IRAQ",
  IraqSaudiAra: "IRAQ-SAUDI ARA",
  Ireland: "IRELAND",
  IsleOfMan: "ISLE OF MAN",
  Israel: "ISRAEL",
  Italy: "ITALY",
  Jamaica: "JAMAICA",
  JanMayen: "JAN MAYEN",
  Japan: "JAPAN",
  Jersey: "JERSEY",
  Jordan: "JORDAN",
  JuanDeNovaI: "JUAN DE NOVA I",
  Kazakhstan: "KAZAKHSTAN",
  Kenya: "KENYA",
  Kiribati: "KIRIBATI",
  Kosovo: "KOSOVO",
  Kuwait: "KUWAIT",
  Kyrgyzstan: "KYRGYZSTAN",
  Laos: "LAOS",
  Latvia: "LATVIA",
  Lebanon: "LEBANON",
  Lesotho: "LESOTHO",
  Liberia: "LIBERIA",
  Libya: "LIBYA",
  Liechtenstein: "LIECHTENSTEIN",
  Lithuania: "LITHUANIA",
  Luxembourg: "LUXEMBOURG",
  Macau: "MACAU",
  Macedonia: "MACEDONIA",
  Madagascar: "MADAGASCAR",
  Malawi: "MALAWI",
  Malaysia: "MALAYSIA",
  Maldives: "MALDIVES",
  Mali: "MALI",
  Malta: "MALTA",
  MarshallIs: "MARSHALL IS",
  Martinique: "MARTINIQUE",
  Mauritania: "MAURITANIA",
  Mauritius: "MAURITIUS",
  Mayotte: "MAYOTTE",
  Mexico: "MEXICO",
  Moldova: "MOLDOVA",
  Monaco: "MONACO",
  Mongolia: "MONGOLIA",
  Montenegro: "MONTENEGRO",
  Montserrat: "MONTSERRAT",
  Morocco: "MOROCCO",
  Mozambique: "MOZAMBIQUE",
  Namibia: "NAMIBIA",
  Nauru: "NAURU",
  Nepal: "NEPAL",
  Netherlands: "NETHERLANDS",
  NetherlandsAn: "NETHERLANDS AN",
  NewCaledonia: "NEW CALEDONIA",
  NewZealand: "NEW ZEALAND",
  Nicaragua: "NICARAGUA",
  Niger: "NIGER",
  Nigeria: "NIGERIA",
  Niue: "NIUE",
  NorfolkIs: "NORFOLK IS",
  NorthKorea: "NORTH KOREA",
  Norway: "NORWAY",
  NotStated: "NOT STATED",
  Oman: "OMAN",
  Pakistan: "PAKISTAN",
  PalestinianTr: "PALESTINIAN TR",
  Panama: "PANAMA",
  PapuaNGuinea: "PAPUA N GUINEA",
  ParacelIss: "PARACEL ISS",
  Paraguay: "PARAGUAY",
  Peru: "PERU",
  Philippines: "PHILIPPINES",
  PitcairnIss: "PITCAIRN ISS",
  Poland: "POLAND",
  Portugal: "PORTUGAL",
  Qatar: "QATAR",
  RepOfPalau: "REP OF PALAU",
  Reunion: "REUNION",
  Romania: "ROMANIA",
  Russia: "RUSSIA",
  Rwanda: "RWANDA",
  SaintMartin: "SAINT MARTIN",
  Samoa: "SAMOA",
  SanMarino: "SAN MARINO",
  SaoTomePrinc: "SAO TOME/PRINC",
  SaudiArabia: "SAUDI ARABIA",
  Senegal: "SENEGAL",
  Serbia: "SERBIA",
  SerbiaMonteng: "SERBIA/MONTENG",
  Seychelles: "SEYCHELLES",
  SierraLeone: "SIERRA LEONE",
  Singapore: "SINGAPORE",
  SintMaarten: "SINT MAARTEN",
  Slovakia: "SLOVAKIA",
  Slovenia: "SLOVENIA",
  SolomonIss: "SOLOMON ISS",
  Somalia: "SOMALIA",
  SouthAfrica: "SOUTH AFRICA",
  SouthGeorgia: "SOUTH GEORGIA",
  SouthKorea: "SOUTH KOREA",
  SouthSudan: "SOUTH SUDAN",
  Spain: "SPAIN",
  SpratleyIss: "SPRATLEY ISS",
  SriLanka: "SRI LANKA",
  StHelena: "ST HELENA",
  StKittsNevis: "ST KITTS/NEVIS",
  StLucia: "ST LUCIA",
  StPierreMiqu: "ST PIERRE/MIQU",
  StVincentGrn: "ST VINCENT/GRN",
  StBarthelemy: "ST/BARTHELEMY",
  Sudan: "SUDAN",
  Suriname: "SURINAME",
  Svalbard: "SVALBARD",
  Sweden: "SWEDEN",
  Switzerland: "SWITZERLAND",
  Syria: "SYRIA",
  Taiwan: "TAIWAN",
  Tajikistan: "TAJIKISTAN",
  TanzaniaURep: "TANZANIA U REP",
  Thailand: "THAILAND",
  TimorLeste: "TIMOR-LESTE",
  Togo: "TOGO",
  Tokelau: "TOKELAU",
  Tonga: "TONGA",
  TrinidadToba: "TRINIDAD/TOBA",
  TromelinIs: "TROMELIN IS",
  Tunisia: "TUNISIA",
  Turkey: "TURKEY",
  Turkmenistan: "TURKMENISTAN",
  TurksCaicosI: "TURKS/CAICOS I",
  Tuvalu: "TUVALU",
  Uganda: "UGANDA",
  Ukraine: "UKRAINE",
  UnitedArabEm: "UNITED ARAB EM",
  UnitedKingdom: "UNITED KINGDOM",
  UnitedStates: "UNITED STATES",
  Uruguay: "URUGUAY",
  UsMinorIslan: "US MINOR ISLAN",
  Uzbekistan: "UZBEKISTAN",
  Vanuatu: "VANUATU",
  VaticanCity: "VATICAN CITY",
  Venezuela: "VENEZUELA",
  Vietnam: "VIETNAM",
  WallisFutuna: "WALLIS/FUTUNA",
  WestBank: "WEST BANK",
  WesternSahara: "WESTERN SAHARA",
  Yemen: "YEMEN",
  Yugoslavia: "YUGOSLAVIA",
  Zambia: "ZAMBIA",
  Zimbabwe: "ZIMBABWE",
} as const;

export type OrgCountry = typeof OrgCountry[keyof typeof OrgCountry];
